{
  "openapi": "3.0.1",
  "info": {
    "version": "2.0.2",
    "title": "Last survivors Api Docs",
    "description": "Showing off how to work with our Api",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [{ "url": "https://last-survivors-back.onrender.com" }],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "User",
      "description": "User endpoint"
    },
    {
      "name": "Avatar",
      "description": "Update avatar endpoint"
    },
    {
      "name": "Boards",
      "description": "Update avatar endpoint"
    },
    {
      "name": "Columns",
      "description": "Update avatar endpoint"
    },
    {
      "name": "Cards",
      "description": "Update avatar endpoint"
    }
  ],
  "paths": {
    "/api/auth/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "security": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Provided email already exists",
            "content": {}
          }
        }
      }
    },
    "/api/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User loginization",
        "parameters": [],
        "security": [],
        "requestBody": {
          "description": "Login's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/api/auth/current": {
      "get": {
        "tags": ["Auth"],
        "summary": "Current user",
        "parameters": [],
        "security": [{ "Bearer": [] }],

        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          }
        }
      }
    },
    "/api/auth/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LogoutResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "User already logouted",
            "content": {}
          }
        }
      }
    },
    "/api/user/{userId}": {
      "patch": {
        "tags": ["User"],
        "summary": "Edit user profile",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "type": "string",
            "description": "ID of user",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Update's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateUserResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "User not found",
            "content": {}
          }
        }
      }
    },
    "/api/avatar/": {
      "patch": {
        "tags": ["Avatar"],
        "summary": "Edit user profile",
        "parameters": [
          {
            "name": "Bearer token",
            "in": "path",
            "type": "string",
            "description": "Token of user",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Update's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateAvatarRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateAvatarResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "User not found",
            "content": {}
          }
        }
      }
    },
    "/api/board": {
      "get": {
        "tags": ["Boards"],
        "summary": "User boards",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BoardsResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "User boards not found",
            "content": {}
          }
        }
      },
      "post": {
        "tags": ["Boards"],
        "summary": "User create board",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Boards's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddBoardRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddBoardResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/api/board/{boardID}": {
      "patch": {
        "tags": ["Boards"],
        "summary": "Edit board",
        "parameters": [
          {
            "name": "boardId",
            "in": "path",
            "type": "string",
            "description": "ID of board",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Boards's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/EditBoardRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EditBoardResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Board not found",
            "content": {}
          }
        }
      },
      "delete": {
        "tags": ["Boards"],
        "summary": "Delete board",
        "parameters": [
          {
            "name": "boardId",
            "in": "path",
            "type": "string",
            "description": "ID of board",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteBoardResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/api/columns": {
      "post": {
        "tags": ["Columns"],
        "summary": "User create column",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Column's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddColumnRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddColumnResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/api/columns/{columnId}": {
      "delete": {
        "tags": ["Columns"],
        "summary": "Delete column",
        "parameters": [
          {
            "name": "columnId",
            "in": "path",
            "type": "string",
            "description": "ID of column",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteColumnResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      },
      "patch": {
        "tags": ["Columns"],
        "summary": "Edit column",
        "parameters": [
          {
            "name": "columnId",
            "in": "path",
            "type": "string",
            "description": "ID of column",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Column's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/EditColumnRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EditColumnResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Column not found",
            "content": {}
          }
        }
      }
    },
    "/api/columns/{boardId}": {
      "get": {
        "tags": ["Columns"],
        "summary": "Get columns by board id",
        "parameters": [
          {
            "name": "boardId",
            "in": "path",
            "type": "string",
            "description": "ID of board",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ColumnsResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/api/cards": {
      "post": {
        "tags": ["Cards"],
        "summary": "User create card",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Card's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddCardRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CardByIdResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/api/cards/{cardId}": {
      "get": {
        "tags": ["Cards"],
        "summary": "Get card by id",
        "parameters": [
          {
            "name": "cardId",
            "in": "path",
            "type": "string",
            "description": "ID of card",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CardByIdResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      },
      "delete": {
        "tags": ["Cards"],
        "summary": "Delete card",
        "parameters": [
          {
            "name": "cardId",
            "in": "path",
            "type": "string",
            "description": "ID of card",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CardByIdResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      },
      "patch": {
        "tags": ["Cards"],
        "summary": "Edit card",
        "parameters": [
          {
            "name": "cardId",
            "in": "path",
            "type": "string",
            "description": "ID of card",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Card's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/EditCardRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CardByIdResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Column not found",
            "content": {}
          }
        }
      }
    },
    "/api/cards/column/{cardId}": {
      "patch": {
        "tags": ["Cards"],
        "summary": "User edit column id in card",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Card's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ChangeColumnRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ChangeColumnResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["username", "email", "password"],
        "properties": {
          "username": {
            "type": "string",
            "description": "User's username",
            "example": "John Doe"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "RegistrationResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "userId": {
              "type": "number",
              "description": "User's id",
              "example": "32143232436545474"
            },
            "username": {
              "type": "string",
              "description": "User's username",
              "example": "32143232436545474"
            },
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "theme": {
              "type": "string",
              "description": "User's theme",
              "example": "light"
            }
          }
        },
        "example": [
          {
            "id": "668e342900f72bd11752128f",
            "username": "Luke Worksas",
            "email": "lu332sasa21@lisoren.com",
            "theme": "light"
          }
        ]
      },
      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "LoginResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "token": {
              "type": "string",
              "description": "User's auth token",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
            },
            "user": {
              "type": "object",
              "description": "User's info",
              "example": "{}"
            }
          }
        },
        "example": [
          {
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
            "user": {
              "id": "668e342900f72ad11752128f",
              "username": "Luke Worksas",
              "email": "lu332sasa21@lisoren.com",
              "theme": "light",
              "avatarURL": "avatarURL"
            }
          }
        ]
      },
      "LogoutResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "message": {
              "type": "string",
              "description": "Logout message",
              "example": "Logout success"
            }
          }
        },
        "example": [
          {
            "message": "Logout success"
          }
        ]
      },
      "UpdateUserRequest": {
        "type": "object",
        "required": [""],
        "properties": {
          "username": {
            "type": "string",
            "description": "User's username",
            "example": "John Doe"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          },
          "theme": {
            "type": "string",
            "description": "User's theme",
            "example": "light"
          }
        }
      },
      "UpdateUserResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "userId": {
              "type": "number",
              "description": "User's id",
              "example": "32143232436545474"
            },
            "username": {
              "type": "string",
              "description": "User's username",
              "example": "32143232436545474"
            },
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "theme": {
              "type": "string",
              "description": "User's theme",
              "example": "light"
            },
            "avatarURL": {
              "type": "string",
              "description": "User's avatar",
              "example": "avatarURL"
            }
          }
        },
        "example": [
          {
            "id": "668e342900f72bd11752128f",
            "username": "John Doe",
            "email": "user@example.com",
            "theme": "light",
            "avatarURL": "avatarURL"
          }
        ]
      },
      "UpdateAvatarRequest": {
        "type": "object",
        "required": ["avatarURL"],
        "properties": {
          "avatarURL": {
            "type": "form-data",
            "description": "User's avatar",
            "example": "form-data"
          }
        }
      },
      "UpdateAvatarResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "avatarURL": {
              "type": "string",
              "description": "User's avatar",
              "example": "avatarURL"
            }
          }
        },
        "example": [
          {
            "avatarURL": "avatarURL"
          }
        ]
      },
      "BoardsResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Board id",
              "example": "683076e09faa82544602e9"
            },
            "name": {
              "type": "string",
              "description": "Board name",
              "example": "Example"
            },
            "owner_id": {
              "type": "string",
              "description": "Board owner id",
              "example": "669836e09faa82544602e9"
            },
            "icon_name": {
              "type": "string",
              "description": "Icon name",
              "example": "icon4"
            },
            "background_url": {
              "type": "string",
              "description": "Background name",
              "example": "background0"
            }
          }
        },
        "example": [
          {
            "_id": "66983076e09faa82544602e9",
            "name": "Aleksa2",
            "owner_id": "6692763db99b0d0ca4b2c400",
            "icon_name": "icon4",
            "background_url": "background0"
          },
          {
            "_id": "6698ec0dd5710c06e9373c",
            "name": "test",
            "owner_id": "6692763db99b0d0ca4b200",
            "icon_name": "icon1",
            "background_url": "background4"
          }
        ]
      },
      "AddBoardRequest": {
        "type": "object",
        "required": ["name", "icon_name", "background_url"],
        "properties": {
          "name": {
            "type": "string",
            "description": "Board name",
            "example": "Example"
          },
          "icon_name": {
            "type": "string",
            "description": "Icon name",
            "example": "icon4"
          },
          "background_url": {
            "type": "string",
            "description": "Background name",
            "example": "background0"
          }
        }
      },
      "AddBoardResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Board id",
              "example": "683076e09faa82544602e9"
            },
            "name": {
              "type": "string",
              "description": "Board name",
              "example": "Example"
            },
            "owner_id": {
              "type": "string",
              "description": "Board owner id",
              "example": "669836e09faa82544602e9"
            },
            "icon_name": {
              "type": "string",
              "description": "Icon name",
              "example": "icon4"
            },
            "background_url": {
              "type": "string",
              "description": "Background name",
              "example": "background0"
            }
          }
        },
        "example": [
          {
            "_id": "6698ec0dd5710c06e9373c",
            "name": "test",
            "owner_id": "6692763db99b0d0ca4b200",
            "icon_name": "icon1",
            "background_url": "background4"
          }
        ]
      },
      "EditBoardRequest": {
        "type": "object",
        "required": [""],
        "properties": {
          "name": {
            "type": "string",
            "description": "Board name",
            "example": "Example"
          },
          "icon_name": {
            "type": "string",
            "description": "Icon name",
            "example": "icon4"
          },
          "background_url": {
            "type": "string",
            "description": "Background name",
            "example": "background0"
          }
        }
      },
      "EditBoardResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Board id",
              "example": "683076e09faa82544602e9"
            },
            "name": {
              "type": "string",
              "description": "Board name",
              "example": "Example"
            },
            "owner_id": {
              "type": "string",
              "description": "Board owner id",
              "example": "669836e09faa82544602e9"
            },
            "icon_name": {
              "type": "string",
              "description": "Icon name",
              "example": "icon4"
            },
            "background_url": {
              "type": "string",
              "description": "Background name",
              "example": "background0"
            }
          }
        },
        "example": [
          {
            "_id": "6698ec0dd5710c06e9373c",
            "name": "test",
            "owner_id": "6692763db99b0d0ca4b200",
            "icon_name": "icon1",
            "background_url": "background4"
          }
        ]
      },
      "DeleteBoardResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Board id",
              "example": "683076e09faa82544602e9"
            },
            "name": {
              "type": "string",
              "description": "Board name",
              "example": "Example"
            },
            "owner_id": {
              "type": "string",
              "description": "Board owner id",
              "example": "669836e09faa82544602e9"
            },
            "icon_name": {
              "type": "string",
              "description": "Icon name",
              "example": "icon4"
            },
            "background_url": {
              "type": "string",
              "description": "Background name",
              "example": "background0"
            }
          }
        },
        "example": [
          {
            "_id": "6698ec0dd5710c06e9373c",
            "name": "test",
            "owner_id": "6692763db99b0d0ca4b200",
            "icon_name": "icon1",
            "background_url": "background4"
          }
        ]
      },
      "AddColumnRequest": {
        "type": "object",
        "required": ["title", "board_id"],
        "properties": {
          "title": {
            "type": "string",
            "description": "Column title",
            "example": "Example"
          },
          "board_id": {
            "type": "string",
            "description": "Board owner id",
            "example": "669836e09faa82544602e9"
          }
        }
      },
      "AddColumnResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "description": "Column title",
              "example": "Example"
            },
            "board_id": {
              "type": "string",
              "description": "Board owner id",
              "example": "669836e09faa82544602e9"
            },
            "_id": {
              "type": "string",
              "description": "Column id",
              "example": "669836e09faa82544602e9"
            }
          }
        },
        "example": [
          {
            "_id": "6698ec0dd5710c06e9373c",
            "title": "Test",
            "board_id": "6692763db99b0d0ca4b200"
          }
        ]
      },
      "ColumnsResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "description": "Column title",
              "example": "Example"
            },
            "board_id": {
              "type": "string",
              "description": "Board owner id",
              "example": "669836e09faa82544602e9"
            },
            "_id": {
              "type": "string",
              "description": "Column id",
              "example": "669836e09faa82544602e9"
            },
            "cards": {
              "type": "array",
              "description": "Column id",
              "example": "[{card},{card},{card}]"
            }
          }
        },
        "example": [
          [
            {
              "_id": "6698d0e3fbce61c0dbe3c044",
              "title": "Test",
              "board_id": "66983076e09faa82544602e9",
              "cards": [
                {
                  "_id": "6698d0f3fbce61c0dbe3c047",
                  "title": "Test",
                  "description": "Test",
                  "priority": "Medium",
                  "deadline": "18/07/2024",
                  "board_id": "66983076e09faa82544602e9",
                  "column_id": "6698d0e3fbce61c0dbe3c044"
                }
              ]
            }
          ]
        ]
      },
      "EditColumnRequest": {
        "type": "object",
        "required": ["title", "board_id"],
        "properties": {
          "title": {
            "type": "string",
            "description": "Board name",
            "example": "Example"
          },
          "board_id": {
            "type": "string",
            "description": "Board name",
            "example": "683076e09faa82544602e9"
          }
        }
      },
      "EditColumnResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Board id",
              "example": "683076e09faa82544602e9"
            },
            "title": {
              "type": "string",
              "description": "Board name",
              "example": "Example"
            },
            "board_id": {
              "type": "string",
              "description": "Board owner id",
              "example": "669836e09faa82544602e9"
            }
          }
        },
        "example": [
          {
            "_id": "669668d583e42253764b1b6a",
            "title": "Test012",
            "board_id": "669276b2e8db04fa68672af7"
          }
        ]
      },
      "DeleteColumnResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Board id",
              "example": "683076e09faa82544602e9"
            },
            "title": {
              "type": "string",
              "description": "Board name",
              "example": "Example"
            },
            "board_id": {
              "type": "string",
              "description": "Board owner id",
              "example": "669836e09faa82544602e9"
            }
          }
        },
        "example": [
          {
            "_id": "6698ec0dd5710c06e9373c",
            "title": "test",
            "board_id": "6692763db99b0d0ca4b200"
          }
        ]
      },
      "CardByIdResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Card id",
              "example": "683076e09faa82544602e9"
            },
            "title": {
              "type": "string",
              "description": "Card name",
              "example": "Example"
            },
            "description": {
              "type": "string",
              "description": "Card description",
              "example": "Example"
            },
            "priority": {
              "type": "string",
              "description": "Card priority",
              "example": "Medium"
            },
            "board_id": {
              "type": "string",
              "description": "Board id",
              "example": "669836e09faa82544602e9"
            },
            "column_id": {
              "type": "string",
              "description": "Column id",
              "example": "669836e09faa82544602e9"
            },
            "deadline": {
              "type": "string",
              "description": "Card deadline",
              "example": "11/11/2024"
            }
          }
        },
        "example": [
          {
            "_id": "6698d2c7fbce61c0dbe3c056",
            "title": "asdasda",
            "description": "asdasd",
            "priority": "High",
            "deadline": "18/07/2024",
            "board_id": "66983076e09faa82544602e9",
            "column_id": "6698d0e3fbce61c0dbe3c044"
          }
        ]
      },
      "EditCardRequest": {
        "type": "array",
        "required": [""],
        "items": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "description": "Card name",
              "example": "Example"
            },
            "description": {
              "type": "string",
              "description": "Card description",
              "example": "Example"
            },
            "priority": {
              "type": "string",
              "description": "Card priority",
              "example": "Medium"
            },
            "board_id": {
              "type": "string",
              "description": "Board id",
              "example": "669836e09faa82544602e9"
            },
            "column_id": {
              "type": "string",
              "description": "Column id",
              "example": "669836e09faa82544602e9"
            },
            "deadline": {
              "type": "string",
              "description": "Card deadline",
              "example": "11/11/2024"
            }
          }
        },
        "example": [
          {
            "title": "asdasda",
            "description": "asdasd",
            "priority": "High",
            "deadline": "18/07/2024",
            "board_id": "66983076e09faa82544602e9",
            "column_id": "6698d0e3fbce61c0dbe3c044"
          }
        ]
      },
      "AddCardRequest": {
        "type": "array",
        "required": [
          "title",
          "board_id",
          "description",
          "priority",
          "column_id",
          "deadline"
        ],
        "items": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "description": "Card name",
              "example": "Example"
            },
            "description": {
              "type": "string",
              "description": "Card description",
              "example": "Example"
            },
            "priority": {
              "type": "string",
              "description": "Card priority",
              "example": "Medium"
            },
            "board_id": {
              "type": "string",
              "description": "Board id",
              "example": "669836e09faa82544602e9"
            },
            "column_id": {
              "type": "string",
              "description": "Column id",
              "example": "669836e09faa82544602e9"
            },
            "deadline": {
              "type": "string",
              "description": "Card deadline",
              "example": "11/11/2024"
            }
          }
        },
        "example": [
          {
            "title": "asdasda",
            "description": "asdasd",
            "priority": "High",
            "deadline": "18/07/2024",
            "board_id": "66983076e09faa82544602e9",
            "column_id": "6698d0e3fbce61c0dbe3c044"
          }
        ]
      },
      "ChangeColumnRequest": {
        "type": "array",
        "required": ["_id", "board_id", "oldColumn_id", "column_id"],
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Card name",
              "example": "Example"
            },
            "items": {
              "type": "object",
              "properties": {
                "board_id": {
                  "type": "string",
                  "description": "Board id",
                  "example": "6836e09faa82544602e9"
                },
                "column_id": {
                  "type": "string",
                  "description": "Column id",
                  "example": "669836efaa82544602e9"
                },
                "oldColumn_id": {
                  "type": "string",
                  "description": "Old column id",
                  "example": "669836e09faa825602e9"
                }
              }
            }
          }
        },
        "example": [
          {
            "_id": "66983076e09faa82544602e9",
            "cardsData": {
              "board_id": "66983076e09faa82544602e9",
              "column_id": "6698d0e3fbce61c0dbe3c044",
              "oldColumn_id": "6698d0e3fbce61c0dbesc23"
            }
          }
        ]
      },
      "ChangeColumnResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Card id",
              "example": "683076e09faa82544602e9"
            },
            "title": {
              "type": "string",
              "description": "Card name",
              "example": "Example"
            },
            "description": {
              "type": "string",
              "description": "Card description",
              "example": "Example"
            },
            "priority": {
              "type": "string",
              "description": "Card priority",
              "example": "Medium"
            },
            "board_id": {
              "type": "string",
              "description": "Board id",
              "example": "669836e09faa82544602e9"
            },
            "column_id": {
              "type": "string",
              "description": "Column id",
              "example": "669836e09faa82544602e9"
            },
            "deadline": {
              "type": "string",
              "description": "Card deadline",
              "example": "11/11/2024"
            },
            "oldColumn_id": {
              "type": "string",
              "description": "Column id",
              "example": "669836e09faa8254460e047"
            }
          }
        },
        "example": [
          {
            "_id": "6698d2c7fbce61c0dbe3c056",
            "title": "asdasda",
            "description": "asdasd",
            "priority": "High",
            "deadline": "18/07/2024",
            "board_id": "66983076e09faa82544602e9",
            "column_id": "6698d0e3fbce61c0dbe3c044",
            "oldColumn_id": "669836e09faa8254460e047"
          }
        ]
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
